name: gaff-intel
static_sites:
- name: nginx-router
  source_dir: nginx
  buildpack_stack: ubuntu-22
  http_port: 80
  routes:
  - path: /
    source:
      type: SERVICE
      name: consumer-dashboard
services:
- name: consumer-dashboard
  github:
    branch: main
    deploy_on_push: true
    repo: conor.mcloughlin/code/property-ml
  build_command: cd apps/consumer-dashboard && npm run build
  run_command: cd apps/consumer-dashboard && npm start
  source_dir: apps/consumer-dashboard
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${SUPABASE_URL}
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${SUPABASE_ANON_KEY}
  - key: SUPABASE_SERVICE_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${SUPABASE_SERVICE_KEY}
  - key: NEXT_PUBLIC_MAPBOX_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: ${MAPBOX_TOKEN}
  - key: NEXT_PUBLIC_APP_URL
    scope: RUN_AND_BUILD_TIME
    value: https://irishpropertydata.com
  - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${STRIPE_PUBLISHABLE_KEY}
  - key: STRIPE_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${STRIPE_SECRET_KEY}
  - key: STRIPE_WEBHOOK_SECRET
    scope: RUN_AND_BUILD_TIME
    value: ${STRIPE_WEBHOOK_SECRET}
  - key: LOCATIONIQ_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${LOCATIONIQ_API_KEY}
  - key: POSTHOG_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${POSTHOG_API_KEY}
  health_check:
    http_path: /
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs

- name: agent-app
  github:
    branch: main
    deploy_on_push: true
    repo: conor.mcloughlin/code/property-ml
  build_command: cd apps/agent-app && npm run build
  run_command: cd apps/agent-app && npm start
  source_dir: apps/agent-app
  http_port: 3000
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${SUPABASE_URL}
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${SUPABASE_ANON_KEY}
  - key: SUPABASE_SERVICE_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${SUPABASE_SERVICE_KEY}
  - key: NEXT_PUBLIC_DATA_URL
    scope: RUN_AND_BUILD_TIME
    value: https://irishpropertydata.com/data.json
  - key: NEXT_PUBLIC_APP_URL
    scope: RUN_AND_BUILD_TIME
    value: https://agents.irishpropertydata.com
  - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${STRIPE_PUBLISHABLE_KEY}
  - key: STRIPE_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${STRIPE_SECRET_KEY}
  health_check:
    http_path: /
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs

databases:
- name: postgres-db
  engine: PG
  version: "14"
  production: false
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
