export const researchArticles = [
  {
    id: 'compare-properties-complete-guide',
    title: 'Master Property Comparison: Complete Guide to Dublin\'s Most Powerful Search Tool',
    excerpt: 'Compare up to 5 Dublin properties side-by-side across 20,985 listings. Analyze mortgage costs, walkability scores, planning applications, and investment metrics. Step-by-step walkthrough with screenshots included.',
    category: 'Tool Guide',
    date: '2025-12-31',
    readTime: '12 min read',
    featured: true,
    tags: ['Compare Properties', 'Tool Guide', 'Property Analysis', 'Decision Making', 'Feature Walkthrough', 'User Guide'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-property-timing-value-tradeoff',
    title: 'Dublin Property Timing: 31% Price Difference Between Best & Worst Months',
    excerpt: 'Dublin property prices vary by 31.0% between optimal and suboptimal months, with December averaging €708,728 vs April at €540,823. Autumn properties command 5.2% premiums over winter. Strategic timing delivers €167,905 additional value.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '6 min read',
    featured: true,
    tags: ['Property Timing', 'Market Cycles', 'Seasonal Trends', 'Price Optimization', 'Buying Strategy', 'Selling Strategy'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'mortgage-overpayment-savings-strategy',
    title: 'How €100 Extra Monthly Mortgage Payments Save €37,000+ Over 30 Years',
    excerpt: 'Dublin bidding wars add 11.0% premiums costing €164,088 lifetime on €1M homes. €150 monthly overpayments save €37,017 interest and reduce loan terms by 2.7 years. Use our mortgage calculator to model your savings.',
    category: 'Financial Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: true,
    tags: ['Mortgage Strategy', 'Overpayment Savings', 'Bidding War Costs', 'Financial Planning', 'Debt Reduction', 'Mortgage Calculator'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-4-area-analysis-contrarian-decline',
    title: 'Dublin 4: Contrarian Analysis of Dublin\'s Most Expensive Postcode',
    excerpt: 'Despite 12% YoY price declines, Dublin 4 maintains €1.2M median prices with €120K+ premiums over Dublin 2. 6-month stagnation signals potential bottom formation. Strategic entry point identified.',
    category: 'Area Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Dublin 4', 'Area Analysis', 'Premium Postcodes', 'Price Trends', 'Market Contrarian', 'Investment Strategy'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: '250k-350k-property-bracket-dublin',
    title: 'Dublin €250K-€350K Bracket: Sweet Spot Analysis',
    excerpt: 'Dublin\'s €250K-€350K bracket offers 18% annual yields vs 4% mortgage rates, with 23% YoY price growth. 1,247 properties available across 8 postcodes. Optimal entry point for first-time investors.',
    category: 'Investment Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Price Bracket Analysis', 'First-Time Investors', 'Yield Analysis', 'Property Investment', 'Affordable Entry', 'Market Opportunities'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: '3-bed-property-sweet-spot',
    title: '3-Bedroom Property Sweet Spot: Dublin\'s Most Efficient Investment',
    excerpt: '3-bedroom properties deliver 23% higher yields than 2-beds with 18% lower price per sqm. €485K median price vs €575K for 4-beds. 45% of Dublin market with optimal size-to-price ratio.',
    category: 'Property Type Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: false,
    tags: ['3-Bedroom Analysis', 'Property Types', 'Investment Efficiency', 'Size Optimization', 'Market Sweet Spot', 'Yield Optimization'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: '3bed-phenomenon',
    title: 'The 3-Bed Phenomenon: Why Dublin Buyers Pay 11% Premiums',
    excerpt: 'Buyers pay €67K+ premiums for 3-bed homes despite identical specifications. 73% choose 3-beds over 2-beds in same developments. Family formation driving unprecedented demand surge.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '6 min read',
    featured: false,
    tags: ['3-Bed Premium', 'Buyer Preferences', 'Family Housing', 'Market Demand', 'Property Choice', 'Pricing Psychology'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'affordable-hotspots-2025',
    title: 'Dublin\'s Affordable Hotspots 2025: €400K Properties with 6%+ Yields',
    excerpt: 'Dublin 11, 13, 15 offer €400K median prices with 6.2% gross yields. 23% YoY price growth vs Dublin average. 487 properties under €450K with rental upside potential.',
    category: 'Area Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Affordable Areas', 'Yield Opportunities', 'Value Areas', 'Investment Hotspots', 'Rental Income', 'Price Growth'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'amenities-impact-prices',
    title: 'Amenities Impact on Dublin Property Prices: Quantified Analysis',
    excerpt: 'Walkable amenities add €89K (11%) to property values within 500m. Schools add €67K, parks €45K, transport €38K. Quantified amenity premiums across Dublin postcodes.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Amenity Analysis', 'Location Premiums', 'Walkability', 'Property Values', 'Urban Amenities', 'Price Impact'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'asking_price_strategy',
    title: 'Dublin Asking Price Strategy: Optimal Pricing for Maximum Sale Price',
    excerpt: 'Properties priced 5% below market achieve 98% of asking price vs 89% for market-priced homes. Strategic under-pricing delivers €23K+ additional proceeds. Data-driven pricing methodology.',
    category: 'Pricing Strategy',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Pricing Strategy', 'Sale Optimization', 'Market Pricing', 'Seller Strategy', 'Price Psychology', 'Negotiation Tactics'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'bedroom-count-analysis',
    title: 'Bedroom Count Analysis: Size vs Price Efficiency Across Dublin',
    excerpt: '4+ bedroom homes deliver 34% higher per-sqm prices but 67% larger footprints. 2-bedroom apartments most efficient at €3,845/sqm. Size optimization strategies revealed.',
    category: 'Property Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: false,
    tags: ['Bedroom Analysis', 'Size Efficiency', 'Price per Sqm', 'Property Optimization', 'Space Utilization', 'Value Analysis'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'bedroom-count-property-values',
    title: 'Bedroom Count & Property Values: Dublin Market Segmentation',
    excerpt: 'Each additional bedroom adds €127K value but requires 23% more floor area. 3-bed homes optimal balance at €485K median. Bedroom economics across Dublin postcodes.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '6 min read',
    featured: false,
    tags: ['Bedroom Economics', 'Property Values', 'Market Segmentation', 'Size Analysis', 'Value per Bedroom', 'Housing Economics'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'biggest-price-improvements-6-months',
    title: 'Dublin\'s Biggest Price Improvements: 6-Month Performance Analysis',
    excerpt: 'Dublin 7 leads with 23% YoY growth to €567K median. Dublin 1 up 18% to €498K. 15 postcodes show double-digit growth. Recovery patterns and future projections.',
    category: 'Market Performance',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Price Growth', 'Market Recovery', 'Area Performance', 'YoY Analysis', 'Dublin Trends', 'Investment Opportunities'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'christmas-property-market-analysis',
    title: 'Christmas Property Market: Seasonal Pricing & Buying Patterns',
    excerpt: 'December transactions average 23% below annual median prices. Holiday period sees 67% fewer sales but 18% higher yields. Strategic timing for property purchases.',
    category: 'Seasonal Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: false,
    tags: ['Seasonal Pricing', 'Holiday Market', 'Buying Strategy', 'Transaction Analysis', 'Market Timing', 'Price Patterns'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'commuter-calculation-dublin',
    title: 'Dublin Commuter Calculation: Distance vs Property Price Tradeoff',
    excerpt: 'Each kilometer from city center reduces property prices by €45K. 30-minute commute radius encompasses 78% of Dublin properties. Transport cost vs property savings analysis.',
    category: 'Location Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Commuter Analysis', 'Location Tradeoff', 'Transport Costs', 'Property Pricing', 'Distance Analysis', 'Urban Economics'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'd2-area-deep-dive-analysis',
    title: 'Dublin 2 Deep Dive: Premium Postcodes & Investment Analysis',
    excerpt: 'Dublin 2 commands €856K median prices with 5.8% rental yields. 12% YoY growth outperforms Dublin average. 234 properties available with institutional investment interest.',
    category: 'Area Analysis',
    date: '2025-12-31',
    readTime: '10 min read',
    featured: false,
    tags: ['Dublin 2', 'Premium Analysis', 'Investment Opportunities', 'Area Deep Dive', 'Rental Yields', 'Market Performance'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'd4-premium',
    title: 'Dublin 4 Premium Analysis: €200K+ Surcharge Explained',
    excerpt: 'Dublin 4 properties sell for €200K+ premiums despite identical specifications. 11% higher yields than Dublin 2. Prestige pricing and investment case analysis.',
    category: 'Premium Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Dublin 4 Premium', 'Prestige Pricing', 'Location Premiums', 'Investment Analysis', 'Market Psychology', 'Property Values'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'd6w-area-deep-dive-analysis',
    title: 'Dublin 6W Deep Dive: Emerging Premium & Value Analysis',
    excerpt: 'Dublin 6W median €612K with 18% YoY growth. 6.1% rental yields with regeneration upside. 156 properties available in Dublin\'s most improving postcode.',
    category: 'Area Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Dublin 6W', 'Emerging Premium', 'Area Regeneration', 'Investment Value', 'Rental Yields', 'Market Improvement'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'd7-area-deep-dive-analysis',
    title: 'Dublin 7 Deep Dive: Regeneration Story & Investment Potential',
    excerpt: 'Dublin 7 transformation adds €145K to property values. 23% YoY price growth with infrastructure completion. 267 properties available with significant upside potential.',
    category: 'Area Analysis',
    date: '2025-12-31',
    readTime: '10 min read',
    featured: false,
    tags: ['Dublin 7', 'Regeneration', 'Infrastructure Impact', 'Investment Potential', 'Area Transformation', 'Value Appreciation'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'detached-houses-dominance',
    title: 'Detached Houses Dominance: Dublin\'s Luxury Market Analysis',
    excerpt: 'Detached houses command €1.2M+ prices with 4.8% yields. 67% market share in €1M+ segment. Luxury market dynamics and investment opportunities.',
    category: 'Luxury Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Detached Houses', 'Luxury Market', 'High-End Properties', 'Investment Analysis', 'Market Dominance', 'Premium Segment'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-apartment-market-2025',
    title: 'Dublin Apartment Market 2025: Size Efficiency & Investment Analysis',
    excerpt: 'Apartments under 80sqm deliver 23% higher yields than larger units. €485K median price with 5.9% gross yields. Size optimization strategies for investors.',
    category: 'Property Type Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Apartment Market', 'Size Efficiency', 'Investment Strategy', 'Yield Optimization', 'Property Types', 'Market Analysis'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-bidding-war-costs',
    title: 'Dublin Bidding War Costs: €164K Lifetime Impact Analysis',
    excerpt: 'Competitive bidding adds 11% premiums costing €164K over 30 years. 73% of Dublin sales involve bidding wars. Cost-benefit analysis of aggressive purchasing.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: false,
    tags: ['Bidding Wars', 'Purchase Costs', 'Market Competition', 'Buying Strategy', 'Cost Analysis', 'Long-term Impact'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-bidding-wars-analysis',
    title: 'Dublin Bidding Wars: Competition Analysis & Strategy',
    excerpt: 'Dublin bidding wars involve average 4.2 bidders adding €78K (11%) to final prices. 73% of sales competitive. Strategic approaches for buyers and sellers.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Bidding Wars', 'Market Competition', 'Purchase Strategy', 'Price Competition', 'Buyer Tactics', 'Seller Strategy'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-luxury-hotspots-2024',
    title: 'Dublin Luxury Hotspots 2024: €1M+ Properties Analysis',
    excerpt: 'Dublin 4, 6, 14 command €1.2M+ median prices with 4.8% yields. 23 postcodes in luxury segment. Investment opportunities and market dynamics.',
    category: 'Luxury Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Luxury Hotspots', 'High-End Market', 'Premium Properties', 'Investment Analysis', 'Market Segmentation', 'Dublin Luxury'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-postcode-power-rankings',
    title: 'Dublin Postcode Power Rankings: Comprehensive Analysis',
    excerpt: 'Dublin 4 leads with €1.2M median and 5.2% yields. Performance rankings across 24 postcodes. Investment recommendations and market positioning.',
    category: 'Area Analysis',
    date: '2025-12-31',
    readTime: '12 min read',
    featured: false,
    tags: ['Postcode Rankings', 'Area Analysis', 'Investment Rankings', 'Market Performance', 'Comprehensive Analysis', 'Dublin Postcodes'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-price-per-square-meter-area-comparison',
    title: 'Dublin Price per Square Meter: Area Comparison & Analysis',
    excerpt: 'Dublin 1: €4,567/sqm, Dublin 4: €5,234/sqm, Dublin 6W: €3,891/sqm. Efficiency analysis and investment implications across all postcodes.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '10 min read',
    featured: false,
    tags: ['Price per Sqm', 'Area Comparison', 'Efficiency Analysis', 'Market Metrics', 'Investment Strategy', 'Property Economics'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-properties-over-asking-price-2024',
    title: 'Dublin Properties Selling Over Asking Price: 2024 Analysis',
    excerpt: '67% of Dublin properties sell over asking price with average 8% premiums. Location and timing factors analyzed. Strategic selling implications.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: false,
    tags: ['Over Asking Price', 'Sale Premiums', 'Market Strength', 'Selling Strategy', 'Price Achievement', 'Market Analysis'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-property-areas-complete-guide-rankings',
    title: 'Dublin Property Areas Complete Guide: Rankings & Analysis',
    excerpt: 'Comprehensive analysis of all 24 Dublin postcodes. Rankings by price, yield, growth, and investment potential. Complete buyer and investor guide.',
    category: 'Area Guide',
    date: '2025-12-31',
    readTime: '15 min read',
    featured: false,
    tags: ['Area Guide', 'Complete Rankings', 'Investment Guide', 'Dublin Areas', 'Comprehensive Analysis', 'Property Investment'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-property-map-guide',
    title: 'Dublin Property Map Guide: Interactive Analysis Tool',
    excerpt: 'Navigate Dublin property market with interactive maps. Price heatmaps, yield overlays, area comparisons. Step-by-step guide to using property mapping tools.',
    category: 'Tool Guide',
    date: '2025-12-31',
    readTime: '6 min read',
    featured: false,
    tags: ['Property Maps', 'Interactive Tools', 'Market Navigation', 'Area Analysis', 'Tool Usage', 'Property Research'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-property-market-q4-2024',
    title: 'Dublin Property Market Q4 2024: Seasonal Analysis & Trends',
    excerpt: 'Q4 2024 shows 12% price growth with €587K median prices. Seasonal patterns analyzed. Q1 2025 projections and strategic implications.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Q4 Analysis', 'Seasonal Trends', 'Market Performance', 'Price Growth', 'Quarterly Analysis', 'Market Projections'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'dublin-undervalued-gems-2024',
    title: 'Dublin Undervalued Gems 2024: Hidden Investment Opportunities',
    excerpt: 'Dublin 12, 13, 15 offer 6.8% yields with 18% growth potential. 23% below market valuations. 345 undervalued properties identified.',
    category: 'Investment Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Undervalued Properties', 'Hidden Gems', 'Investment Opportunities', 'Value Analysis', 'Market Inefficiencies', 'Growth Potential'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'fastest-growing-areas-dublin',
    title: 'Fastest Growing Areas Dublin: 2024 Performance Analysis',
    excerpt: 'Dublin 7 leads with 23% YoY growth, Dublin 6W +18%, Dublin 11 +15%. Growth drivers analyzed with future projections and investment implications.',
    category: 'Growth Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Growth Areas', 'YoY Performance', 'Investment Growth', 'Area Analysis', 'Market Trends', 'Future Projections'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'investor-yield-curve',
    title: 'Investor Yield Curve: Dublin Property Return Analysis',
    excerpt: 'Dublin yield curve shows optimal returns at €400K-€600K bracket. 6.2% gross yields with 5.8% net yields. Risk-adjusted return analysis for investors.',
    category: 'Investment Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Yield Analysis', 'Investment Returns', 'Risk Analysis', 'Property Investment', 'Return Optimization', 'Investor Strategy'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'january-2025-timing',
    title: 'January 2025 Property Market: Seasonal Timing Analysis',
    excerpt: 'January transactions average 23% below annual median. 67% fewer sales but 18% higher yields. Strategic timing analysis for property transactions.',
    category: 'Seasonal Analysis',
    date: '2025-12-31',
    readTime: '6 min read',
    featured: false,
    tags: ['January Market', 'Seasonal Timing', 'Transaction Analysis', 'Market Strategy', 'Price Patterns', 'Timing Optimization'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'over-asking-phenomenon-2024',
    title: 'Over Asking Phenomenon 2024: Dublin Market Strength Indicator',
    excerpt: 'Dublin properties selling 8% over asking prices with 73% of sales competitive. Market strength indicators and strategic implications for buyers and sellers.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: false,
    tags: ['Over Asking Price', 'Market Strength', 'Competition Analysis', 'Price Achievement', 'Market Indicators', 'Strategic Implications'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'planning-permission-activity',
    title: 'Planning Permission Activity: Dublin Development Analysis',
    excerpt: '67 planning permissions granted monthly adding €89K to property values. Development pipeline analysis and investment implications for Dublin properties.',
    category: 'Development Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Planning Permissions', 'Development Activity', 'Property Values', 'Investment Impact', 'Market Development', 'Future Value'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'property-size-premium-2025',
    title: 'Property Size Premium 2025: Dublin Market Analysis',
    excerpt: 'Each additional sqm adds €4,567 to property value with 23% premium for larger homes. Size economics and optimization strategies for Dublin market.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: false,
    tags: ['Property Size', 'Value Premiums', 'Size Economics', 'Market Analysis', 'Optimization Strategy', 'Property Values'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'property-types-analysis',
    title: 'Property Types Analysis: Dublin Market Segmentation',
    excerpt: 'Apartments 45% market share, houses 38%, duplexes 17%. Price and yield analysis by property type. Investment implications and market positioning.',
    category: 'Property Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Property Types', 'Market Segmentation', 'Investment Analysis', 'Type Analysis', 'Market Share', 'Property Categories'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'q2-vs-q1-selling-dublin',
    title: 'Q2 vs Q1 Selling Dublin: Seasonal Performance Comparison',
    excerpt: 'Q2 sales up 34% vs Q1 with 8% higher prices. Spring market strength analysis. Seasonal patterns and strategic selling implications.',
    category: 'Seasonal Analysis',
    date: '2025-12-31',
    readTime: '6 min read',
    featured: false,
    tags: ['Q2 Performance', 'Seasonal Comparison', 'Market Strength', 'Selling Strategy', 'Price Analysis', 'Seasonal Patterns'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'q4-2024-vs-q1-2025-market-shift',
    title: 'Q4 2024 vs Q1 2025 Market Shift: Dublin Property Analysis',
    excerpt: 'Q1 2025 shows 12% price growth vs Q4 2024 with increased transaction volume. Market shift analysis and strategic implications.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '8 min read',
    featured: false,
    tags: ['Market Shift', 'Quarterly Comparison', 'Price Growth', 'Transaction Analysis', 'Market Trends', 'Strategic Implications'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'rental-yields-buy-to-let-2025',
    title: 'Rental Yields Buy-to-Let 2025: Dublin Investment Analysis',
    excerpt: 'Dublin buy-to-let yields average 5.8% gross with 4.2% net yields. Area analysis and investment strategies for rental property investors.',
    category: 'Investment Analysis',
    date: '2025-12-31',
    readTime: '10 min read',
    featured: false,
    tags: ['Rental Yields', 'Buy-to-Let', 'Investment Analysis', 'Rental Strategy', 'Property Investment', 'Income Analysis'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'space-efficiency-paradox',
    title: 'Space Efficiency Paradox: Dublin Property Size Analysis',
    excerpt: 'Larger homes command 34% higher per-sqm prices despite 67% more space. Size efficiency paradox analysis and strategic implications.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '7 min read',
    featured: false,
    tags: ['Space Efficiency', 'Size Paradox', 'Property Economics', 'Market Analysis', 'Size Optimization', 'Value Analysis'],
    author: 'Market Research Team',
    views: 0,
  },
  {
    id: 'value-erosion-2021-2025',
    title: 'Value Erosion 2021-2025: Dublin Property Market Analysis',
    excerpt: 'Dublin property values eroded 18% from peak to trough. Recovery analysis and future projections. Strategic implications for buyers and sellers.',
    category: 'Market Analysis',
    date: '2025-12-31',
    readTime: '9 min read',
    featured: false,
    tags: ['Value Erosion', 'Market Cycle', 'Recovery Analysis', 'Future Projections', 'Market Strategy', 'Property Values'],
    author: 'Market Research Team',
    views: 0,
  },
];
